#!/bin/sh

awk '
function norm(x,    s, i) {
	for (i in x)
		s += x[i]
	for (i in x)
		x[i] /= s	
}

BEGIN {
	s = "2 1.8 2 1 1"
	split(s, x)
	s = "1.8 2 3 3 5"
	split(s, y)
	norm(x)
	norm(y)
	for (i  in x)
		print x[i], y[i], x[i]/y[i]
}'